//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.28 at 10:12:42 PM COT 
//


package ec.espe.edu.arqsoftware.clienteactivotarjeta.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ec.espe.edu.arqsoftware.clienteactivotarjeta.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ec.espe.edu.arqsoftware.clienteactivotarjeta.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CrearTarjetaClienteRequest }
     * 
     */
    public CrearTarjetaClienteRequest createCrearTarjetaClienteRequest() {
        return new CrearTarjetaClienteRequest();
    }

    /**
     * Create an instance of {@link TarjetaClienteRQ }
     * 
     */
    public TarjetaClienteRQ createTarjetaClienteRQ() {
        return new TarjetaClienteRQ();
    }

    /**
     * Create an instance of {@link CrearTarjetaClienteResponse }
     * 
     */
    public CrearTarjetaClienteResponse createCrearTarjetaClienteResponse() {
        return new CrearTarjetaClienteResponse();
    }

    /**
     * Create an instance of {@link TarjetaClienteRS }
     * 
     */
    public TarjetaClienteRS createTarjetaClienteRS() {
        return new TarjetaClienteRS();
    }

    /**
     * Create an instance of {@link ListarTransaccionesFechasRequest }
     * 
     */
    public ListarTransaccionesFechasRequest createListarTransaccionesFechasRequest() {
        return new ListarTransaccionesFechasRequest();
    }

    /**
     * Create an instance of {@link TransaccionRQ }
     * 
     */
    public TransaccionRQ createTransaccionRQ() {
        return new TransaccionRQ();
    }

    /**
     * Create an instance of {@link ListarTransaccionesFechasResponse }
     * 
     */
    public ListarTransaccionesFechasResponse createListarTransaccionesFechasResponse() {
        return new ListarTransaccionesFechasResponse();
    }

    /**
     * Create an instance of {@link TransaccionRS }
     * 
     */
    public TransaccionRS createTransaccionRS() {
        return new TransaccionRS();
    }

}
