//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.28 at 10:12:42 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://espe.edu.ec/arqsoftware/activotarjeta/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ec.espe.edu.arqsoftware.clienteactivotarjeta.wsdl;
